CREATE USER cucumber IDENTIFIED BY {{ db_password }}
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;
GRANT DBA TO cucumber;

CREATE USER test IDENTIFIED BY {{ db_password }}
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;
GRANT DBA TO test;

commit;